package org.example.dao;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.example.entity.ItemDao;

import java.util.List;

@Mapper
public interface ItemDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Sat Jul 23 18:38:59 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Sat Jul 23 18:38:59 CST 2022
     */
    int insert(ItemDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Sat Jul 23 18:38:59 CST 2022
     */
    int insertSelective(ItemDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Sat Jul 23 18:38:59 CST 2022
     */
    ItemDao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Sat Jul 23 18:38:59 CST 2022
     */
    int updateByPrimaryKeySelective(ItemDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Sat Jul 23 18:38:59 CST 2022
     */
    int updateByPrimaryKey(ItemDao record);

    //查询所有商品信息
    List<ItemDao> listItem();

    //下单成功后增加商品销量
    int increaseSales(@Param("id") Integer id, @Param("amount") Integer amount);

}