package org.example.dao;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.example.entity.ItemStockDao;

@Mapper
public interface ItemStockDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbggenerated Sat Jul 23 18:38:59 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbggenerated Sat Jul 23 18:38:59 CST 2022
     */
    int insert(ItemStockDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbggenerated Sat Jul 23 18:38:59 CST 2022
     */
    int insertSelective(ItemStockDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbggenerated Sat Jul 23 18:38:59 CST 2022
     */
    ItemStockDao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbggenerated Sat Jul 23 18:38:59 CST 2022
     */
    int updateByPrimaryKeySelective(ItemStockDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbggenerated Sat Jul 23 18:38:59 CST 2022
     */
    int updateByPrimaryKey(ItemStockDao record);

    //通过 item id 获得商品库存
    ItemStockDao selectByItemId(Integer itemId);

    //落单减库存
    int decreaseStock(@Param("itemId") Integer itemId, @Param("amount") Integer amount);
}