package org.example.dao;

import org.apache.ibatis.annotations.Mapper;
import org.example.entity.OrderDao;
@Mapper
public interface OrderDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbggenerated Sat Jul 23 21:41:32 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbggenerated Sat Jul 23 21:41:32 CST 2022
     */
    int insert(OrderDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbggenerated Sat Jul 23 21:41:32 CST 2022
     */
    int insertSelective(OrderDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbggenerated Sat Jul 23 21:41:32 CST 2022
     */
    OrderDao selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbggenerated Sat Jul 23 21:41:32 CST 2022
     */
    int updateByPrimaryKeySelective(OrderDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbggenerated Sat Jul 23 21:41:32 CST 2022
     */
    int updateByPrimaryKey(OrderDao record);
}