package org.example.dao;

import org.apache.ibatis.annotations.Mapper;
import org.example.entity.SequenceDao;

@Mapper
public interface SequenceDaoMapper {

    SequenceDao getSequenceByName(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbggenerated Sat Jul 23 22:10:09 CST 2022
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbggenerated Sat Jul 23 22:10:09 CST 2022
     */
    int insert(SequenceDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbggenerated Sat Jul 23 22:10:09 CST 2022
     */
    int insertSelective(SequenceDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbggenerated Sat Jul 23 22:10:09 CST 2022
     */
    SequenceDao selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbggenerated Sat Jul 23 22:10:09 CST 2022
     */
    int updateByPrimaryKeySelective(SequenceDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbggenerated Sat Jul 23 22:10:09 CST 2022
     */
    int updateByPrimaryKey(SequenceDao record);
}