package org.example.dao;

import org.apache.ibatis.annotations.Mapper;
import org.example.entity.StockLogDao;
@Mapper
public interface StockLogDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbggenerated Sun Aug 14 11:43:56 CST 2022
     */
    int deleteByPrimaryKey(String stockLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbggenerated Sun Aug 14 11:43:56 CST 2022
     */
    int insert(StockLogDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbggenerated Sun Aug 14 11:43:56 CST 2022
     */
    int insertSelective(StockLogDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbggenerated Sun Aug 14 11:43:56 CST 2022
     */
    StockLogDao selectByPrimaryKey(String stockLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbggenerated Sun Aug 14 11:43:56 CST 2022
     */
    int updateByPrimaryKeySelective(StockLogDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbggenerated Sun Aug 14 11:43:56 CST 2022
     */
    int updateByPrimaryKey(StockLogDao record);
}