package org.example.dao;

import org.apache.ibatis.annotations.Mapper;
import org.example.entity.UserDao;

@Mapper
public interface UserDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Sat Jul 23 12:37:34 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Sat Jul 23 12:37:34 CST 2022
     */
    int insert(UserDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Sat Jul 23 12:37:34 CST 2022
     */
    int insertSelective(UserDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Sat Jul 23 12:37:34 CST 2022
     */
    UserDao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Sat Jul 23 12:37:34 CST 2022
     */
    int updateByPrimaryKeySelective(UserDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Sat Jul 23 12:37:34 CST 2022
     */
    int updateByPrimaryKey(UserDao record);

    //根据电话号码取得用户对象
    UserDao selectByTelphone(String telphone);

}