package org.example.dao;

import org.apache.ibatis.annotations.Mapper;
import org.example.entity.UserPasswordDao;

@Mapper
public interface UserPasswordDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbggenerated Sat Jul 23 12:37:34 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbggenerated Sat Jul 23 12:37:34 CST 2022
     */
    int insert(UserPasswordDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbggenerated Sat Jul 23 12:37:34 CST 2022
     */
    int insertSelective(UserPasswordDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbggenerated Sat Jul 23 12:37:34 CST 2022
     */
    UserPasswordDao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbggenerated Sat Jul 23 12:37:34 CST 2022
     */
    int updateByPrimaryKeySelective(UserPasswordDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbggenerated Sat Jul 23 12:37:34 CST 2022
     */
    int updateByPrimaryKey(UserPasswordDao record);

//    根据用户 id 查询密码
    UserPasswordDao selectByUserId(Integer UserId);
}