package org.example.entity;

/*
* 创建自增序列 --> 用于商品交易订单号的自增序列部分
* */
public class SequenceDao {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.name
     *
     * @mbggenerated Sat Jul 23 22:10:09 CST 2022
     */
    private String name;        //描述 eg:order_info

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.current_value
     *
     * @mbggenerated Sat Jul 23 22:10:09 CST 2022
     */
    private Integer currentValue;       //当前起始值

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.step
     *
     * @mbggenerated Sat Jul 23 22:10:09 CST 2022
     */
    private Integer step;               //增长步长

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info.name
     *
     * @return the value of sequence_info.name
     *
     * @mbggenerated Sat Jul 23 22:10:09 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info.name
     *
     * @param name the value for sequence_info.name
     *
     * @mbggenerated Sat Jul 23 22:10:09 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info.current_value
     *
     * @return the value of sequence_info.current_value
     *
     * @mbggenerated Sat Jul 23 22:10:09 CST 2022
     */
    public Integer getCurrentValue() {
        return currentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info.current_value
     *
     * @param currentValue the value for sequence_info.current_value
     *
     * @mbggenerated Sat Jul 23 22:10:09 CST 2022
     */
    public void setCurrentValue(Integer currentValue) {
        this.currentValue = currentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info.step
     *
     * @return the value of sequence_info.step
     *
     * @mbggenerated Sat Jul 23 22:10:09 CST 2022
     */
    public Integer getStep() {
        return step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info.step
     *
     * @param step the value for sequence_info.step
     *
     * @mbggenerated Sat Jul 23 22:10:09 CST 2022
     */
    public void setStep(Integer step) {
        this.step = step;
    }
}